teams = [
    "Real Madrid",
    "FC Barcelona",
    "Manchester United",
    "Liverpool",
    "Bayern Munich",
    "Juventus",
    "Paris Saint-Germain",
    "AC Milan",
    "Inter Milan",
    "Chelsea",
    "Arsenal",
    "Manchester City",
    "Borussia Dortmund",
    "Atletico Madrid",
    "Napoli",
    "AS Roma",
    "Tottenham Hotspur",
    "Sporting CP",
    "Bayer Leverkusen",
    "Santos",
]

teams_url = {
    "Real Madrid" : "https://onefootball.com/en/team/real-madrid-26",
    "FC Barcelona" : "https://onefootball.com/en/team/barcelona-5",
    "Manchester United" : "https://onefootball.com/en/team/manchester-united-21",
    "Liverpool" : "https://onefootball.com/en/team/liverpool-fc-18",
    "Bayern Munich" : "https://onefootball.com/en/team/bayern-munich-6",
    "Juventus" : "https://onefootball.com/en/team/juventus-17",
    "Paris Saint-Germain" : "https://onefootball.com/en/team/psg-263",
    "AC Milan" : "https://onefootball.com/en/team/milan-23",
    "Inter Milan" : "https://onefootball.com/en/team/inter-16",
    "Chelsea" : "https://onefootball.com/en/team/chelsea-9",
    "Arsenal" : "https://onefootball.com/en/team/arsenal-2",
    "Manchester City" : "https://onefootball.com/en/team/manchester-city-209",
    "Borussia Dortmund" : "https://onefootball.com/en/team/borussia-dortmund-155",
    "Atletico Madrid" : "https://onefootball.com/en/team/atletico-de-madrid-3",
    "Napoli" : "https://onefootball.com/en/team/napoli-191",
    "AS Roma" : "https://onefootball.com/en/team/roma-145",
    "Tottenham Hotspur" : "https://onefootball.com/en/team/tottenham-hotspur-202",
    "Sporting CP" : "https://onefootball.com/en/team/sporting-cp-140",
    "Bayer Leverkusen" : "https://onefootball.com/en/team/bayer-leverkusen-162",
    "Santos" : "https://onefootball.com/en/team/santos-1798",
}

teams_url_results = {
    "Real Madrid" : "https://onefootball.com/en/team/real-madrid-26/results",
    "FC Barcelona" : "https://onefootball.com/en/team/barcelona-5/results",
    "Manchester United" : "https://onefootball.com/en/team/manchester-united-21/results",
    "Liverpool" : "https://onefootball.com/en/team/liverpool-fc-18/results",
    "Bayern Munich" : "https://onefootball.com/en/team/bayern-munich-6/results",
    "Juventus" : "https://onefootball.com/en/team/juventus-17/results",
    "Paris Saint-Germain" : "https://onefootball.com/en/team/psg-263/results",
    "AC Milan" : "https://onefootball.com/en/team/milan-23/results",
    "Inter Milan" : "https://onefootball.com/en/team/inter-16/results",
    "Chelsea" : "https://onefootball.com/en/team/chelsea-9/results",
    "Arsenal" : "https://onefootball.com/en/team/arsenal-2/results",
    "Manchester City" : "https://onefootball.com/en/team/manchester-city-209/results",
    "Borussia Dortmund" : "https://onefootball.com/en/team/borussia-dortmund-155/results",
    "Atletico Madrid" : "https://onefootball.com/en/team/atletico-de-madrid-3/results",
    "Napoli" : "https://onefootball.com/en/team/napoli-191/results",
    "AS Roma" : "https://onefootball.com/en/team/roma-145/results",
    "Tottenham Hotspur" : "https://onefootball.com/en/team/tottenham-hotspur-202/results",
    "Sporting CP" : "https://onefootball.com/en/team/sporting-cp-140/results",
    "Bayer Leverkusen" : "https://onefootball.com/en/team/bayer-leverkusen-162/results",
    "Santos" : "https://onefootball.com/en/team/santos-1798/results",
}
